### ISSUE TITLE
Nicht kompatibel mit REDAXO 5.9

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/iconpicker#8]
<img width="802" alt="Bildschirmfoto 2020-02-04 um 11 15 05" src="https://user-images.githubusercontent.com/791247/73735486-9d8d0d00-473f-11ea-81ca-091e4579c796.png">

**Comment by skerbis** [comment]
Ich habe eine 1.1.0 erstellt. Hier ist der Vendor auf 1.4.0 gesetzt. Das ist die letzte FA 4.x kompatible Version. Sie funktioniert auch mit dem jQuery ab REDAXO 5.9 @lexplatt - Ich habe schnell einen Release gemacht, da die Zeit drängte.

**Comment by lexplatt** [comment]
Super! Danke
